apiVersion: v1
kind: Service
metadata:
  name: result-server-svc
  labels:
    app: search
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    app: search