apiVersion: v1
kind: Service
metadata:
  name: web-server-svc
  labels:
    app: web-server
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: web-server